# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Documents\pyCharm\ContactAngleGUI\ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UiMainWindow(object):

    def __init__(self, main_window):
        self.window = main_window
        self.centralwidget = QtWidgets.QWidget(self.window)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.brightness_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.brightness_slider = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.sharpness_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.sharpness_slider = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.contrast_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.contrast_slider = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.saturation_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.saturation_slider = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.iso_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.iso_slider = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.actionExit = QtWidgets.QAction(self.window)
        self.actionLoad = QtWidgets.QAction(self.window)
        self.actionSave = QtWidgets.QAction(self.window)
        self.actionAbout = QtWidgets.QAction(self.window)
        self.actionContact = QtWidgets.QAction(self.window)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(self.window)
        self.menubar = QtWidgets.QMenuBar(self.window)
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.setup_ui()

    def setup_ui(self):
        self.window.setObjectName("main_window")
        self.window.resize(1280, 1920)
        self.window.setAutoFillBackground(False)

        self.centralwidget.setObjectName("centralwidget")

        self.label.setGeometry(QtCore.QRect(0, 50, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAutoFillBackground(True)
        self.label.setObjectName("label")

        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 110, 441, 531))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")

        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.brightness_label.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.brightness_label.setFont(font)
        self.brightness_label.setAutoFillBackground(True)
        self.brightness_label.setObjectName("brightness_label")
        self.verticalLayout.addWidget(self.brightness_label)

        self.brightness_slider.setAutoFillBackground(True)
        self.brightness_slider.setMaximum(100)
        self.brightness_slider.setProperty("value", 50)
        self.brightness_slider.setOrientation(QtCore.Qt.Horizontal)
        self.brightness_slider.setInvertedAppearance(False)
        self.brightness_slider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.brightness_slider.setTickInterval(5)
        self.brightness_slider.setObjectName("brightness_slider")
        self.verticalLayout.addWidget(self.brightness_slider)

        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.sharpness_label.setFont(font)
        self.sharpness_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sharpness_label.setAutoFillBackground(True)
        self.sharpness_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.sharpness_label.setObjectName("sharpness_label")
        self.verticalLayout.addWidget(self.sharpness_label)

        self.sharpness_slider.setAutoFillBackground(True)
        self.sharpness_slider.setMinimum(-100)
        self.sharpness_slider.setMaximum(100)
        self.sharpness_slider.setOrientation(QtCore.Qt.Horizontal)
        self.sharpness_slider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.sharpness_slider.setTickInterval(10)
        self.sharpness_slider.setObjectName("sharpness_slider")
        self.verticalLayout.addWidget(self.sharpness_slider)

        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.contrast_label.setFont(font)
        self.contrast_label.setAutoFillBackground(True)
        self.contrast_label.setObjectName("contrast_label")
        self.verticalLayout.addWidget(self.contrast_label)

        self.contrast_slider.setAutoFillBackground(True)
        self.contrast_slider.setMinimum(-100)
        self.contrast_slider.setMaximum(100)
        self.contrast_slider.setOrientation(QtCore.Qt.Horizontal)
        self.contrast_slider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.contrast_slider.setTickInterval(10)
        self.contrast_slider.setObjectName("contrast_slider")
        self.verticalLayout.addWidget(self.contrast_slider)

        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.saturation_label.setFont(font)
        self.saturation_label.setAutoFillBackground(True)
        self.saturation_label.setObjectName("saturation_label")
        self.verticalLayout.addWidget(self.saturation_label)

        self.saturation_slider.setEnabled(True)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.saturation_slider.sizePolicy().hasHeightForWidth())
        self.saturation_slider.setSizePolicy(size_policy)
        self.saturation_slider.setAutoFillBackground(True)
        self.saturation_slider.setMinimum(-100)
        self.saturation_slider.setMaximum(100)
        self.saturation_slider.setOrientation(QtCore.Qt.Horizontal)
        self.saturation_slider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.saturation_slider.setTickInterval(10)
        self.saturation_slider.setObjectName("saturation_slider")
        self.verticalLayout.addWidget(self.saturation_slider)

        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.iso_label.setFont(font)
        self.iso_label.setAutoFillBackground(True)
        self.iso_label.setObjectName("iso_label")
        self.verticalLayout.addWidget(self.iso_label)

        self.iso_slider.setAutoFillBackground(True)
        self.iso_slider.setMinimum(100)
        self.iso_slider.setMaximum(800)
        self.iso_slider.setOrientation(QtCore.Qt.Horizontal)
        self.iso_slider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.iso_slider.setTickInterval(100)
        self.iso_slider.setObjectName("iso_slider")
        self.verticalLayout.addWidget(self.iso_slider)

        self.graphicsView.setGeometry(QtCore.QRect(480, 0, 800, 640))
        self.graphicsView.setObjectName("graphicsView")

        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(480, 640, 801, 231))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")

        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.pushButton.setGeometry(QtCore.QRect(220, 770, 101, 41))
        self.pushButton.setObjectName("pushButton")

        self.pushButton_2.setGeometry(QtCore.QRect(340, 770, 91, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.window.setCentralWidget(self.centralwidget)

        self.statusbar.setObjectName("statusbar")
        self.window.setStatusBar(self.statusbar)

        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 21))
        self.menubar.setObjectName("menubar")

        self.menuFile.setObjectName("menuFile")

        self.menuHelp.setObjectName("menuHelp")
        self.window.setMenuBar(self.menubar)

        self.actionExit.setObjectName("actionExit")

        self.actionLoad.setObjectName("actionLoad")

        self.actionSave.setObjectName("actionSave")

        self.actionAbout.setObjectName("actionAbout")

        self.actionContact.setObjectName("actionContact")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionContact)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslate_ui()
        self.brightness_slider.valueChanged['int'].connect(self.brightness_label.setNum)  # type: ignore
        self.sharpness_slider.valueChanged['int'].connect(self.sharpness_label.setNum)  # type: ignore
        self.contrast_slider.valueChanged['int'].connect(self.contrast_label.setNum)  # type: ignore
        self.saturation_slider.valueChanged['int'].connect(self.saturation_label.setNum)  # type: ignore
        self.iso_slider.valueChanged['int'].connect(self.iso_label.setNum)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(self.window)

    def retranslate_ui(self):
        _translate = QtCore.QCoreApplication.translate
        self.window.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Settings"))
        self.brightness_label.setText(_translate("MainWindow", "Brightness"))
        self.sharpness_label.setText(_translate("MainWindow", "Sharpness"))
        self.contrast_label.setText(_translate("MainWindow", "Contrast"))
        self.saturation_label.setText(_translate("MainWindow", "Saturation"))
        self.iso_label.setText(_translate("MainWindow", "ISO"))
        self.pushButton.setText(_translate("MainWindow", "Reset"))
        self.pushButton_2.setText(_translate("MainWindow", "Apply"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionLoad.setText(_translate("MainWindow", "Load..."))
        self.actionSave.setText(_translate("MainWindow", "Save..."))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionContact.setText(_translate("MainWindow", "Contact"))
